### ISSUE TITLE
History of "Parrot", What was based on ?

### ISSUE THREAD

**Issue by nadamedhat27** [nadamedhat27/LDP-Task#2]
Write in summary these tow things in markdown or HTML, Just to be in a nice view.

**Comment by nadamedhat27** [comment]
you see can what i wrote in ubuntu to get inspiration

**Comment by nadamedhat27** [comment]
you can use this website https://readme.so/editor to test the output

**Comment by AumerEhab162** [comment]
https://readme.so/editor%C2%A0to gives me "this page couldn't be found"

**Comment by nadamedhat27** [comment]
https://readme.so/editor
